services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gradle_student_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_gradle:/var/lib/postgresql/data

volumes:
  postgres_data_gradle: