server:
  port: 8888
  servlet:
    context-path: /student-service

spring:
  application:
    name: student-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:gradle_student_service}?currentSchema=${DB_SCHEMA:public}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
